[package]
name = "day_09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
nom.workspace = true
glam.workspace = true
itertools.workspace = true
geo = "0.32.0"
